name: Feature matrix

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        feature: ["-DWITH_SDL=OFF", "-DWITH_TTS=OFF", "-DWITH_BABEL=OFF", "-DSOUND=QT", "-DWITH_KDE=ON", "-DJPEGLIB=IJG"]

    runs-on: ubuntu-22.04
    container:
      image: amd64/ubuntu:22.04
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update packages
        run: apt update

      - name: Install packages
        run: DEBIAN_FRONTEND=noninteractive apt install -y
          build-essential
          cmake
          extra-cmake-modules
          git
          libfmt-dev
          libfontconfig1-dev
          libfreetype-dev
          libjpeg-dev
          libkf5kio-dev
          libkf5service-dev
          libmpg123-dev
          libopenmpt-dev
          libsdl2-mixer-dev
          libsndfile-dev
          libspeechd-dev
          libturbojpeg0-dev
          qtbase5-dev
          qtbase5-dev-tools
          qtmultimedia5-dev

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr ${{ matrix.feature }} -DWITH_INTERPRETERS=OFF -DWITH_LAUNCHER=OFF

      - name: Build
        run: |
          cd build
          make -j`nproc`
          make install DESTDIR=/tmp/gargoyle
