name: macOS (DMG)

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update brew
        run: brew update

      - name: Install packages
        run: brew install fmt jpeg-turbo pkg-config sdl2 sdl2_mixer

      - name: Build
        run: |
          echo $(date +"%Y%m%d").$(echo $GITHUB_SHA | cut -b 1-7) > VERSION
          sh gargoyle_osx.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Gargoyle.dmg
          path: gargoyle*.dmg
