name: macOS (Qt)

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update brew
        run: brew update

      - name: Install packages
        run: brew install fmt libopenmpt libsndfile libvorbis mpg123 pkg-config qt6 libpng jpeg

      - name: Build (Qt)
        run: |
          mkdir build-cmake
          cd build-cmake
          cmake .. -DINTERFACE=QT -DSOUND=QT -DWITH_QT6=ON -DCMAKE_FIND_FRAMEWORK=LAST
          make -j`sysctl -n hw.ncpu`
